version: '3.7'

services:
  pd:
    image: pingcap/pd:v5.3.1
    ports:
      - "2379"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
#      - ./data:/data
      - ./logs:/logs
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
      - --data-dir=/data/pd
      - --config=/pd.toml
      - --log-file=/logs/pd.log

  tikv:
    image: pingcap/tikv:v5.3.1
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
#      - ./data:/data
      - ./logs:/logs
    ulimits:
      nofile:
        soft: 82920
        hard: 82920
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --data-dir=/data/tikv
      - --pd=pd:2379
      - --config=/tikv.toml
      - --log-file=/logs/tikv.log
    depends_on:
      - "pd"

  tidb:
    image: pingcap/tidb:v5.3.1
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
      - ./logs:/logs
    command:
      - --store=tikv
      - --path=pd:2379
      - --config=/tidb.toml
      - --log-file=/logs/tidb.log
      - --advertise-address=tidb
    depends_on:
      - "tikv"
