version: "3.7"

#volumes:
#  yb-master-data-1:
#  yb-tserver-data-1:

services:
  yb-master:
    image: yugabytedb/yugabyte:2.11.1.0-b305
    container_name: yb-master-n1
#    volumes:
#      - yb-master-data-1:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=${MASTER_ADDRESSES}",
                "--rpc_bind_addresses=0.0.0.0:7100",
                "--server_broadcast_addresses=${MASTER_BROADCAST_ADDRESSES}",
                "--use_private_ip=never",
                "--replication_factor=3"]
    ports:
      - "7000:7000"
      - "7100:7100"
#    network_mode: host
    environment:
      - SERVICE_7000_NAME=yb-master

  yb-tserver:
    image: yugabytedb/yugabyte:2.11.1.0-b305
    container_name: yb-tserver-n1
#    volumes:
#      - yb-tserver-data-1:/mnt/tserver
    command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--ysql_max_connections=500",
                "--rpc_bind_addresses=0.0.0.0:9100",
                "--server_broadcast_addresses=${TSERVER_BROADCAST_ADDRESSES}",
                "--use_private_ip=never",
                "--tserver_master_addrs=${MASTER_ADDRESSES}"]
    ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
      - "9100:9100"
#    network_mode: host
    environment:
      - SERVICE_5433_NAME=ysql
      - SERVICE_9042_NAME=ycql
      - SERVICE_6379_NAME=yedis
      - SERVICE_9000_NAME=yb-tserver
    depends_on:
      - yb-master